server:
  port: 8888

backend:
  messaging:
    manageProductsQueue: products.manage.queue
    host: 172.18.0.7
    user: mquser
    password: mquser
    vhost: uasnt

endpoints:
  enabled: false
  health:
    enabled: true